'use client'
import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, Dices, Menu, Moon, Search, Sun, Type, X, Zap } from 'lucide-react'
import { categories } from '@/data/categories'
import { tools, type ToolDefinition } from '@/data/tools'

export function Header() {
 const [open,setOpen]=useState(false); const [dark,setDark]=useState(false)
 useEffect(()=>{const root=document.documentElement; let stored: string | null = null; try { stored = window.localStorage.getItem('byousoku.theme') } catch { /* ignore */ } const isDark = stored ? stored === 'dark' : root.classList.contains('dark'); setDark(isDark); root.classList.toggle('dark',isDark); root.classList.toggle('light',!isDark)},[])
 const toggle=()=>{const nextDark=!dark; setDark(nextDark); document.documentElement.classList.toggle('dark',nextDark); document.documentElement.classList.toggle('light',!nextDark); try { window.localStorage.setItem('byousoku.theme', nextDark ? 'dark' : 'light') } catch { /* ignore */ }}
 return <header className="sticky top-0 z-50 border-b border-border/70 bg-background/85 backdrop-blur-xl transition-colors duration-300"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5"><Link href="/" className="flex items-center gap-2 font-semibold tracking-tight"><span className="grid size-8 place-items-center rounded-xl bg-primary text-primary-foreground"><Zap size={17} fill="currentColor" /></span><span>秒速ツール</span></Link><nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><Link href="/" className="hover:text-foreground">ホーム</Link><a href="#categories" className="hover:text-foreground">カテゴリー</a><a href="#popular" className="hover:text-foreground">人気ツール</a><a href="#new" className="hover:text-foreground">新着ツール</a></nav><div className="flex items-center gap-2"><button type="button" aria-label="テーマ切り替え" onClick={toggle} className="grid size-9 place-items-center rounded-lg text-muted-foreground hover:bg-muted hover:text-foreground">{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button type="button" aria-label="メニュー" onClick={()=>setOpen(!open)} className="grid size-9 place-items-center rounded-lg hover:bg-muted md:hidden">{open?<X size={19}/>:<Menu size={19}/>}</button></div></div>{open&&<nav className="animate-fade-up border-t border-border bg-background px-5 py-4 md:hidden"><div className="mx-auto flex max-w-6xl flex-col gap-4 text-sm"><Link href="/" onClick={()=>setOpen(false)}>ホーム</Link><a href="#categories" onClick={()=>setOpen(false)}>カテゴリー</a><a href="#popular" onClick={()=>setOpen(false)}>人気ツール</a></div></nav>}</header>
}
export function Footer(){return <footer className="border-t border-border bg-card"><div className="mx-auto flex max-w-6xl flex-col gap-6 px-5 py-10 md:flex-row md:items-center md:justify-between"><div><Link href="/" className="flex items-center gap-2 font-semibold"><span className="grid size-7 place-items-center rounded-lg bg-primary text-primary-foreground"><Zap size={15} fill="currentColor"/></span>秒速ツール</Link><p className="mt-2 text-sm text-muted-foreground">面倒なことを、1秒で。</p></div><div className="flex flex-wrap gap-x-5 gap-y-2 text-sm text-muted-foreground"><Link href="/">ホーム</Link><a href="#categories">カテゴリー</a><a href="#popular">人気ツール</a><Link href="/terms">利用規約</Link><Link href="/privacy">プライバシーポリシー</Link><Link href="/contact">お問い合わせ</Link></div><p className="text-xs text-muted-foreground">© 2026 秒速ツール</p></div></footer>}
export function AdSlot(){const srcDoc=`<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:0;background:transparent"><script type="text/javascript" charset="utf-8" src="https://adm.shinobi.jp/s/35c6779d0fa252f5a810f17a43736fed"><\/script></body></html>`;return <div className="mx-auto my-8 w-full max-w-[728px]"><iframe title="広告" srcDoc={srcDoc} className="block h-[90px] w-full border-0" loading="lazy"/></div>}
function Icon({name}:{name:string}){const icons:any={Type,Search,Dices,Zap}; const I=icons[name]||Zap; return <I size={20}/>}
export function ToolCard({tool}:{tool:ToolDefinition}){return <Link href={`/tools/${tool.slug}`} className="group animate-fade-up flex min-h-40 flex-col justify-between rounded-2xl border border-border bg-card p-5 shadow-sm transition-all hover:-translate-y-1 hover:border-primary/40 hover:shadow-lg"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><Icon name={tool.icon}/></span><div className="flex items-center gap-2">{tool.new&&<span className="rounded-full bg-primary px-2 py-0.5 text-xs font-semibold text-primary-foreground">NEW</span>}<ArrowRight size={18} className="text-muted-foreground transition-transform group-hover:translate-x-1 group-hover:text-primary"/></div></div><div><h3 className="mt-4 font-semibold">{tool.name}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{tool.description}</p></div></Link>}
export function SearchTools(){const [q,setQ]=useState(''); const results=useMemo(()=>tools.filter(t=>(t.name+t.description+(categories.find(c=>c.slug===t.categorySlug)?.name||'')).includes(q)),[q]); return <div className="mx-auto max-w-3xl"><div className="flex items-center gap-3 rounded-2xl border border-border bg-card px-5 py-4 shadow-lg shadow-primary/5 focus-within:border-primary"><Search className="text-primary" size={21}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="文字数カウント、割引計算、ルーレット..." className="min-w-0 flex-1 bg-transparent text-base outline-none placeholder:text-muted-foreground"/></div>{q&&<div className="animate-fade-up mt-3 grid gap-2 rounded-2xl border border-border bg-card p-3 shadow-xl">{results.length?results.slice(0,6).map(t=><Link key={t.slug} href={`/tools/${t.slug}`} className="flex items-center justify-between rounded-xl px-3 py-2 text-sm hover:bg-muted"><span>{t.name}</span><ArrowRight size={15}/></Link>):<p className="px-3 py-4 text-sm text-muted-foreground">該当するツールが見つかりませんでした</p>}</div>}</div>}
export function Roulette(){const [items,setItems]=useState(['今日のご飯','映画を見る','散歩する','読書する']); const [value,setValue]=useState(''); const [history,setHistory]=useState<string[]>([]); const [copied,setCopied]=useState(false); const spin=()=>{const picked=items[Math.floor(Math.random()*items.length)]||''; setValue(picked); if(picked)setHistory(h=>[picked,...h.filter(x=>x!==picked)].slice(0,10))}; const copy=async()=>{if(!value)return; try{await navigator.clipboard.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),1200)}catch{}}; return <div className="rounded-3xl border border-primary/20 bg-primary/5 p-6 md:p-8"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-primary text-primary-foreground"><Dices/></span><div><p className="text-sm font-medium text-primary">遊び・SNS</p><h2 className="text-xl font-semibold">究極の決定ルーレット</h2></div></div><p className="mt-5 text-sm leading-6 text-muted-foreground">迷ったときは、答えをルーレットに任せてみよう。</p><div className="mt-5 flex flex-wrap gap-2">{items.map((x,i)=><button type="button" key={`${x}-${i}`} onClick={()=>setItems(items.filter((_,j)=>j!==i))} className="rounded-full border border-border bg-card px-3 py-1.5 text-sm hover:border-destructive">{x} ×</button>)}</div><div className="mt-4 flex gap-2"><input aria-label="選択肢を追加" id="roulette-add" className="min-w-0 flex-1 rounded-xl border border-border bg-card px-3 py-2 text-sm outline-none focus:border-primary" placeholder="選択肢を追加" onKeyDown={e=>{if(e.key==='Enter'&&e.currentTarget.value.trim()){setItems([...items,e.currentTarget.value.trim()]);e.currentTarget.value=''}}}/><button type="button" onClick={spin} className="rounded-xl bg-primary px-5 py-2 text-sm font-medium text-primary-foreground">回す</button></div>{value&&<div className="animate-pop-in mt-6 rounded-2xl bg-card p-5 text-center"><p className="text-xs tracking-widest text-muted-foreground">RESULT</p><p className="mt-2 text-2xl font-bold text-primary">{value}</p><div className="mt-4 flex justify-center gap-3"><button type="button" onClick={spin} className="text-sm text-muted-foreground underline underline-offset-4">もう一度回す</button><button type="button" onClick={copy} className="text-sm text-muted-foreground underline underline-offset-4">{copied?'コピー済み':'結果をコピー'}</button></div></div>}{history.length>0&&<div className="mt-6 rounded-2xl border border-border bg-card p-4"><p className="text-xs font-medium text-muted-foreground">履歴（直近10件）</p><ul className="mt-2 space-y-1 text-sm">{history.map((h,i)=><li key={`${h}-${i}`} className="text-muted-foreground">{i+1}. {h}</li>)}</ul></div>}</div>}
