import { notFound } from 'next/navigation'
import { ChevronRight, Copy, RotateCcw } from 'lucide-react'
import { getTool, tools } from '@/data/tools'
import { AdSlot, Footer, Header, ToolCard } from '@/components/site-shell'
import { ToolWorkbench } from '@/components/tool-workbench'

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://example.com'

export function generateStaticParams(){return tools.map(t=>({slug:t.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params; const tool=getTool(slug); if(!tool)return {}; const url=`${siteUrl}/tools/${tool.slug}`; return {title:tool.name, description:`${tool.description}。登録不要ですぐに利用できる無料ツールです。`, alternates:{canonical:url}, openGraph:{type:'website', url, title:tool.name, description:`${tool.description}。登録不要ですぐに利用できる無料ツールです。`, images:[{url:'/ogp.png',width:1200,height:630,alt:tool.name}]}, twitter:{card:'summary_large_image', title:tool.name, description:`${tool.description}。登録不要ですぐに利用できる無料ツールです。`, images:['/ogp.png']}}}
export default async function ToolPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params; const tool=getTool(slug); if(!tool)notFound(); const related=tools.filter(t=>t.categorySlug===tool.categorySlug&&t.slug!==tool.slug).slice(0,3); const url=`${siteUrl}/tools/${tool.slug}`; return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'SoftwareApplication',name:tool.name,url,description:tool.description,applicationCategory:'UtilityApplication',operatingSystem:'Any',inLanguage:'ja-JP',offers:{'@type':'Offer',price:'0',priceCurrency:'JPY'}})}}/><Header/><main className="mx-auto max-w-6xl px-5 py-10 md:py-14"><div className="flex items-center gap-2 text-sm text-muted-foreground"><a href="/">ホーム</a><ChevronRight size={15}/><span>{tool.name}</span></div><div className="mt-10 max-w-3xl"><p className="text-sm font-medium text-primary">{tool.categorySlug}</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">{tool.name}</h1><p className="mt-4 text-muted-foreground">{tool.description}</p></div><AdSlot/><ToolWorkbench kind={tool.implementation}/><section className="mt-16 grid gap-10 lg:grid-cols-[1fr_1fr]"><div><h2 className="text-xl font-semibold">使い方</h2><ol className="mt-5 space-y-4">{tool.steps.map((step,i)=><li key={step} className="flex gap-4"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-primary text-sm font-semibold text-primary-foreground">{i+1}</span><p className="pt-1 text-sm leading-6 text-muted-foreground">{step}</p></li>)}</ol></div><div><h2 className="text-xl font-semibold">よくある質問</h2><div className="mt-5 space-y-3">{tool.faqs.map(f=><details key={f.q} className="rounded-xl border border-border bg-card p-4"><summary className="cursor-pointer text-sm font-medium">{f.q}</summary><p className="mt-3 text-sm leading-6 text-muted-foreground">{f.a}</p></details>)}</div></div></section><AdSlot/><section className="mt-16"><h2 className="text-xl font-semibold">関連ツール</h2><div className="mt-5 grid gap-4 md:grid-cols-3">{related.map(t=><ToolCard key={t.slug} tool={t}/>)}</div></section></main><Footer/></>}
